/**
 * Extended seed to push total movies to 1000+
 */
import mysql from "mysql2/promise";
import dotenv from "dotenv";
dotenv.config();

const DB_URL = process.env.DATABASE_URL;

function slugify(text) {
  return text.toLowerCase().replace(/[^a-z0-9\s-]/g, "").replace(/\s+/g, "-").replace(/-+/g, "-").trim();
}

// 500+ more movies across all eras and genres
const MOVIES = [
  // Action/Adventure
  { title: "Mission: Impossible – Fallout", year: 2018, imdbRating: 7.7, rtScore: 97, genres: ["Action", "Adventure", "Thriller"] },
  { title: "John Wick", year: 2014, imdbRating: 7.4, rtScore: 86, genres: ["Action", "Crime", "Thriller"] },
  { title: "John Wick: Chapter 2", year: 2017, imdbRating: 7.5, rtScore: 89, genres: ["Action", "Crime", "Thriller"] },
  { title: "John Wick: Chapter 3", year: 2019, imdbRating: 7.4, rtScore: 89, genres: ["Action", "Crime", "Thriller"] },
  { title: "John Wick: Chapter 4", year: 2023, imdbRating: 7.7, rtScore: 94, genres: ["Action", "Crime", "Thriller"] },
  { title: "The Bourne Identity", year: 2002, imdbRating: 7.9, rtScore: 83, genres: ["Action", "Mystery", "Thriller"] },
  { title: "The Bourne Supremacy", year: 2004, imdbRating: 7.8, rtScore: 81, genres: ["Action", "Mystery", "Thriller"] },
  { title: "The Bourne Ultimatum", year: 2007, imdbRating: 8.1, rtScore: 93, genres: ["Action", "Mystery", "Thriller"] },
  { title: "Casino Royale", year: 2006, imdbRating: 8.0, rtScore: 95, genres: ["Action", "Adventure", "Thriller"] },
  { title: "Skyfall", year: 2012, imdbRating: 7.8, rtScore: 92, genres: ["Action", "Adventure", "Thriller"] },
  { title: "Speed", year: 1994, imdbRating: 7.3, rtScore: 94, genres: ["Action", "Adventure", "Crime"] },
  { title: "The Rock", year: 1996, imdbRating: 7.4, rtScore: 67, genres: ["Action", "Adventure", "Thriller"] },
  { title: "Con Air", year: 1997, imdbRating: 6.9, rtScore: 56, genres: ["Action", "Crime", "Thriller"] },
  { title: "Air Force One", year: 1997, imdbRating: 6.9, rtScore: 78, genres: ["Action", "Drama", "Thriller"] },
  { title: "Armageddon", year: 1998, imdbRating: 6.7, rtScore: 38, genres: ["Action", "Adventure", "Sci-Fi"] },
  { title: "The Fugitive", year: 1993, imdbRating: 7.8, rtScore: 96, genres: ["Action", "Crime", "Drama"] },
  { title: "Point Break", year: 1991, imdbRating: 7.3, rtScore: 68, genres: ["Action", "Crime", "Thriller"] },
  { title: "Lethal Weapon", year: 1987, imdbRating: 7.6, rtScore: 82, genres: ["Action", "Crime", "Thriller"] },
  { title: "Beverly Hills Cop", year: 1984, imdbRating: 7.3, rtScore: 83, genres: ["Action", "Comedy", "Crime"] },
  { title: "Commando", year: 1985, imdbRating: 6.7, rtScore: 71, genres: ["Action", "Adventure", "Thriller"] },
  { title: "Predator", year: 1987, imdbRating: 7.8, rtScore: 81, genres: ["Action", "Adventure", "Sci-Fi"] },
  { title: "Total Recall", year: 1990, imdbRating: 7.5, rtScore: 82, genres: ["Action", "Sci-Fi", "Thriller"] },
  { title: "True Lies", year: 1994, imdbRating: 7.3, rtScore: 71, genres: ["Action", "Comedy", "Thriller"] },
  { title: "Face/Off", year: 1997, imdbRating: 7.3, rtScore: 92, genres: ["Action", "Crime", "Sci-Fi"] },
  { title: "The Fifth Element", year: 1997, imdbRating: 7.7, rtScore: 71, genres: ["Action", "Adventure", "Sci-Fi"] },
  { title: "Wanted", year: 2008, imdbRating: 6.7, rtScore: 71, genres: ["Action", "Crime", "Fantasy"] },
  { title: "Taken", year: 2008, imdbRating: 7.8, rtScore: 58, genres: ["Action", "Crime", "Thriller"] },
  { title: "The Expendables", year: 2010, imdbRating: 6.5, rtScore: 41, genres: ["Action", "Adventure", "Thriller"] },
  { title: "Dredd", year: 2012, imdbRating: 7.1, rtScore: 78, genres: ["Action", "Sci-Fi", "Thriller"] },
  { title: "Atomic Blonde", year: 2017, imdbRating: 6.7, rtScore: 78, genres: ["Action", "Mystery", "Thriller"] },
  // Superhero
  { title: "Iron Man", year: 2008, imdbRating: 7.9, rtScore: 94, genres: ["Action", "Adventure", "Sci-Fi"] },
  { title: "Iron Man 2", year: 2010, imdbRating: 7.0, rtScore: 73, genres: ["Action", "Adventure", "Sci-Fi"] },
  { title: "Iron Man 3", year: 2013, imdbRating: 7.1, rtScore: 79, genres: ["Action", "Adventure", "Sci-Fi"] },
  { title: "Thor", year: 2011, imdbRating: 7.0, rtScore: 77, genres: ["Action", "Adventure", "Fantasy"] },
  { title: "Thor: Ragnarok", year: 2017, imdbRating: 7.9, rtScore: 93, genres: ["Action", "Adventure", "Comedy"] },
  { title: "Captain America: The First Avenger", year: 2011, imdbRating: 6.9, rtScore: 80, genres: ["Action", "Adventure", "Sci-Fi"] },
  { title: "Captain America: The Winter Soldier", year: 2014, imdbRating: 7.7, rtScore: 90, genres: ["Action", "Adventure", "Sci-Fi"] },
  { title: "Captain America: Civil War", year: 2016, imdbRating: 7.8, rtScore: 91, genres: ["Action", "Adventure", "Sci-Fi"] },
  { title: "The Avengers", year: 2012, imdbRating: 8.0, rtScore: 91, genres: ["Action", "Adventure", "Sci-Fi"] },
  { title: "Avengers: Age of Ultron", year: 2015, imdbRating: 7.3, rtScore: 76, genres: ["Action", "Adventure", "Sci-Fi"] },
  { title: "Avengers: Infinity War", year: 2018, imdbRating: 8.4, rtScore: 85, genres: ["Action", "Adventure", "Sci-Fi"] },
  { title: "Avengers: Endgame", year: 2019, imdbRating: 8.4, rtScore: 94, genres: ["Action", "Adventure", "Drama"] },
  { title: "Guardians of the Galaxy", year: 2014, imdbRating: 8.0, rtScore: 92, genres: ["Action", "Adventure", "Comedy"] },
  { title: "Black Panther", year: 2018, imdbRating: 7.3, rtScore: 96, genres: ["Action", "Adventure", "Sci-Fi"] },
  { title: "Doctor Strange", year: 2016, imdbRating: 7.5, rtScore: 89, genres: ["Action", "Adventure", "Fantasy"] },
  { title: "Spider-Man: Homecoming", year: 2017, imdbRating: 7.4, rtScore: 92, genres: ["Action", "Adventure", "Sci-Fi"] },
  { title: "Spider-Man: Far From Home", year: 2019, imdbRating: 7.4, rtScore: 90, genres: ["Action", "Adventure", "Sci-Fi"] },
  { title: "Spider-Man: No Way Home", year: 2021, imdbRating: 8.2, rtScore: 93, genres: ["Action", "Adventure", "Fantasy"] },
  { title: "Batman Begins", year: 2005, imdbRating: 8.2, rtScore: 84, genres: ["Action", "Adventure"] },
  { title: "The Dark Knight Rises", year: 2012, imdbRating: 8.4, rtScore: 87, genres: ["Action", "Thriller"] },
  { title: "Man of Steel", year: 2013, imdbRating: 7.0, rtScore: 56, genres: ["Action", "Adventure", "Fantasy"] },
  { title: "Wonder Woman", year: 2017, imdbRating: 7.4, rtScore: 93, genres: ["Action", "Adventure", "Fantasy"] },
  { title: "Aquaman", year: 2018, imdbRating: 6.9, rtScore: 65, genres: ["Action", "Adventure", "Fantasy"] },
  { title: "Shazam!", year: 2019, imdbRating: 7.0, rtScore: 90, genres: ["Action", "Adventure", "Comedy"] },
  { title: "X-Men", year: 2000, imdbRating: 7.4, rtScore: 82, genres: ["Action", "Adventure", "Sci-Fi"] },
  { title: "X2: X-Men United", year: 2003, imdbRating: 7.5, rtScore: 88, genres: ["Action", "Adventure", "Sci-Fi"] },
  { title: "X-Men: Days of Future Past", year: 2014, imdbRating: 8.0, rtScore: 91, genres: ["Action", "Adventure", "Sci-Fi"] },
  { title: "Logan", year: 2017, imdbRating: 8.1, rtScore: 93, genres: ["Action", "Drama", "Sci-Fi"] },
  { title: "Deadpool", year: 2016, imdbRating: 8.0, rtScore: 84, genres: ["Action", "Adventure", "Comedy"] },
  { title: "Deadpool 2", year: 2018, imdbRating: 7.7, rtScore: 84, genres: ["Action", "Adventure", "Comedy"] },
  // Drama
  { title: "The Green Mile", year: 1999, imdbRating: 8.6, rtScore: 78, genres: ["Crime", "Drama", "Fantasy"] },
  { title: "Cast Away", year: 2000, imdbRating: 7.8, rtScore: 89, genres: ["Adventure", "Drama", "Romance"] },
  { title: "A Beautiful Day in the Neighborhood", year: 2019, imdbRating: 7.3, rtScore: 95, genres: ["Biography", "Drama"] },
  { title: "The Pursuit of Happyness", year: 2006, imdbRating: 8.0, rtScore: 67, genres: ["Biography", "Drama"] },
  { title: "Philadelphia", year: 1993, imdbRating: 7.7, rtScore: 80, genres: ["Drama"] },
  { title: "The Revenant", year: 2015, imdbRating: 8.0, rtScore: 78, genres: ["Action", "Adventure", "Drama"] },
  { title: "12 Years a Slave", year: 2013, imdbRating: 8.1, rtScore: 96, genres: ["Biography", "Drama", "History"] },
  { title: "The Theory of Everything", year: 2014, imdbRating: 7.7, rtScore: 80, genres: ["Biography", "Drama", "Romance"] },
  { title: "The Imitation Game", year: 2014, imdbRating: 8.0, rtScore: 90, genres: ["Biography", "Drama", "Thriller"] },
  { title: "Bohemian Rhapsody", year: 2018, imdbRating: 7.9, rtScore: 61, genres: ["Biography", "Drama", "Music"] },
  { title: "Rocketman", year: 2019, imdbRating: 7.3, rtScore: 89, genres: ["Biography", "Drama", "Music"] },
  { title: "Ray", year: 2004, imdbRating: 7.7, rtScore: 80, genres: ["Biography", "Drama", "Music"] },
  { title: "Walk the Line", year: 2005, imdbRating: 7.9, rtScore: 82, genres: ["Biography", "Drama", "Music"] },
  { title: "Lincoln", year: 2012, imdbRating: 7.4, rtScore: 89, genres: ["Biography", "Drama", "History"] },
  { title: "Selma", year: 2014, imdbRating: 7.5, rtScore: 99, genres: ["Biography", "Drama", "History"] },
  { title: "Hidden Figures", year: 2016, imdbRating: 7.8, rtScore: 93, genres: ["Biography", "Drama", "History"] },
  { title: "The Big Short", year: 2015, imdbRating: 7.8, rtScore: 89, genres: ["Biography", "Comedy", "Drama"] },
  { title: "Spotlight", year: 2015, imdbRating: 8.1, rtScore: 97, genres: ["Biography", "Crime", "Drama"] },
  { title: "The Social Network", year: 2010, imdbRating: 7.8, rtScore: 96, genres: ["Biography", "Drama"] },
  { title: "Moneyball", year: 2011, imdbRating: 7.6, rtScore: 94, genres: ["Biography", "Drama", "Sport"] },
  { title: "The Wolf of Wall Street", year: 2013, imdbRating: 8.2, rtScore: 77, genres: ["Biography", "Crime", "Drama"] },
  { title: "American Hustle", year: 2013, imdbRating: 7.2, rtScore: 93, genres: ["Crime", "Drama"] },
  { title: "The Artist", year: 2011, imdbRating: 7.9, rtScore: 96, genres: ["Comedy", "Drama", "Romance"] },
  { title: "The King's Speech", year: 2010, imdbRating: 8.0, rtScore: 95, genres: ["Biography", "Drama", "History"] },
  { title: "Birdman", year: 2014, imdbRating: 7.7, rtScore: 91, genres: ["Comedy", "Drama"] },
  { title: "Whiplash", year: 2014, imdbRating: 8.5, rtScore: 94, genres: ["Drama", "Music"] },
  { title: "Room", year: 2015, imdbRating: 8.1, rtScore: 97, genres: ["Drama", "Thriller"] },
  { title: "Manchester by the Sea", year: 2016, imdbRating: 7.8, rtScore: 96, genres: ["Drama"] },
  { title: "Moonlight", year: 2016, imdbRating: 7.4, rtScore: 98, genres: ["Drama"] },
  { title: "Three Billboards Outside Ebbing, Missouri", year: 2017, imdbRating: 8.1, rtScore: 90, genres: ["Crime", "Drama"] },
  { title: "Call Me by Your Name", year: 2017, imdbRating: 7.9, rtScore: 95, genres: ["Drama", "Romance"] },
  { title: "Lady Bird", year: 2017, imdbRating: 7.4, rtScore: 99, genres: ["Comedy", "Drama"] },
  { title: "The Shape of Water", year: 2017, imdbRating: 7.3, rtScore: 92, genres: ["Adventure", "Drama", "Fantasy"] },
  { title: "Green Book", year: 2018, imdbRating: 8.2, rtScore: 78, genres: ["Biography", "Comedy", "Drama"] },
  { title: "The Favourite", year: 2018, imdbRating: 7.5, rtScore: 94, genres: ["Biography", "Drama", "History"] },
  { title: "Marriage Story", year: 2019, imdbRating: 7.9, rtScore: 95, genres: ["Drama", "Romance"] },
  { title: "The Irishman", year: 2019, imdbRating: 7.8, rtScore: 96, genres: ["Biography", "Crime", "Drama"] },
  { title: "Nomadland", year: 2020, imdbRating: 7.3, rtScore: 93, genres: ["Drama"] },
  { title: "The Father", year: 2020, imdbRating: 8.3, rtScore: 98, genres: ["Drama", "Thriller"] },
  { title: "Promising Young Woman", year: 2020, imdbRating: 7.5, rtScore: 90, genres: ["Crime", "Drama", "Thriller"] },
  { title: "Minari", year: 2020, imdbRating: 7.5, rtScore: 99, genres: ["Drama"] },
  { title: "Sound of Metal", year: 2019, imdbRating: 7.8, rtScore: 97, genres: ["Drama", "Music"] },
  { title: "The Power of the Dog", year: 2021, imdbRating: 6.9, rtScore: 94, genres: ["Drama", "Western"] },
  { title: "CODA", year: 2021, imdbRating: 8.0, rtScore: 73, genres: ["Drama", "Music", "Romance"] },
  { title: "Belfast", year: 2021, imdbRating: 7.3, rtScore: 88, genres: ["Biography", "Drama"] },
  { title: "Licorice Pizza", year: 2021, imdbRating: 7.4, rtScore: 91, genres: ["Comedy", "Drama", "Romance"] },
  { title: "Spencer", year: 2021, imdbRating: 6.9, rtScore: 84, genres: ["Biography", "Drama"] },
  { title: "The Banshees of Inisherin", year: 2022, imdbRating: 7.7, rtScore: 97, genres: ["Comedy", "Drama"] },
  { title: "Tár", year: 2022, imdbRating: 7.5, rtScore: 91, genres: ["Drama", "Music"] },
  { title: "Women Talking", year: 2022, imdbRating: 7.3, rtScore: 90, genres: ["Drama"] },
  { title: "The Whale", year: 2022, imdbRating: 7.7, rtScore: 66, genres: ["Drama"] },
  { title: "Aftersun", year: 2022, imdbRating: 7.6, rtScore: 96, genres: ["Drama"] },
  { title: "Past Lives", year: 2023, imdbRating: 7.9, rtScore: 98, genres: ["Drama", "Romance"] },
  { title: "American Fiction", year: 2023, imdbRating: 7.5, rtScore: 91, genres: ["Comedy", "Drama"] },
  { title: "Maestro", year: 2023, imdbRating: 7.0, rtScore: 76, genres: ["Biography", "Drama", "Music"] },
  { title: "Nyad", year: 2023, imdbRating: 7.0, rtScore: 83, genres: ["Biography", "Drama", "Sport"] },
  // Horror/Thriller
  { title: "The Conjuring", year: 2013, imdbRating: 7.5, rtScore: 86, genres: ["Horror", "Mystery", "Thriller"] },
  { title: "The Conjuring 2", year: 2016, imdbRating: 7.3, rtScore: 80, genres: ["Horror", "Mystery", "Thriller"] },
  { title: "Annabelle", year: 2014, imdbRating: 5.4, rtScore: 29, genres: ["Horror", "Mystery", "Thriller"] },
  { title: "It", year: 2017, imdbRating: 7.3, rtScore: 86, genres: ["Horror", "Mystery"] },
  { title: "It Chapter Two", year: 2019, imdbRating: 6.5, rtScore: 62, genres: ["Horror", "Mystery"] },
  { title: "Us", year: 2019, imdbRating: 6.8, rtScore: 93, genres: ["Horror", "Mystery", "Thriller"] },
  { title: "Nope", year: 2022, imdbRating: 6.9, rtScore: 83, genres: ["Horror", "Mystery", "Sci-Fi"] },
  { title: "The Black Phone", year: 2021, imdbRating: 7.3, rtScore: 84, genres: ["Horror", "Mystery", "Thriller"] },
  { title: "Scream", year: 1996, imdbRating: 7.4, rtScore: 79, genres: ["Horror", "Mystery"] },
  { title: "Halloween", year: 1978, imdbRating: 7.7, rtScore: 96, genres: ["Horror", "Thriller"] },
  { title: "A Nightmare on Elm Street", year: 1984, imdbRating: 7.5, rtScore: 95, genres: ["Horror"] },
  { title: "Friday the 13th", year: 1980, imdbRating: 6.4, rtScore: 63, genres: ["Horror", "Mystery", "Thriller"] },
  { title: "The Exorcist", year: 1973, imdbRating: 8.1, rtScore: 83, genres: ["Horror"] },
  { title: "Rosemary's Baby", year: 1968, imdbRating: 8.0, rtScore: 98, genres: ["Drama", "Horror", "Mystery"] },
  { title: "The Omen", year: 1976, imdbRating: 7.5, rtScore: 85, genres: ["Horror", "Mystery", "Thriller"] },
  { title: "Poltergeist", year: 1982, imdbRating: 7.3, rtScore: 87, genres: ["Horror", "Mystery", "Thriller"] },
  { title: "Alien", year: 1979, imdbRating: 8.5, rtScore: 98, genres: ["Horror", "Sci-Fi"] },
  { title: "Aliens", year: 1986, imdbRating: 8.4, rtScore: 98, genres: ["Action", "Adventure", "Sci-Fi"] },
  { title: "Alien 3", year: 1992, imdbRating: 6.4, rtScore: 45, genres: ["Action", "Horror", "Sci-Fi"] },
  { title: "Prometheus", year: 2012, imdbRating: 7.0, rtScore: 73, genres: ["Adventure", "Mystery", "Sci-Fi"] },
  { title: "The Thing", year: 1982, imdbRating: 8.2, rtScore: 84, genres: ["Horror", "Mystery", "Sci-Fi"] },
  { title: "The Fly", year: 1986, imdbRating: 7.5, rtScore: 91, genres: ["Drama", "Horror", "Sci-Fi"] },
  { title: "Misery", year: 1990, imdbRating: 7.8, rtScore: 90, genres: ["Drama", "Horror", "Thriller"] },
  { title: "Cape Fear", year: 1991, imdbRating: 7.3, rtScore: 74, genres: ["Crime", "Drama", "Thriller"] },
  { title: "The Sixth Sense", year: 1999, imdbRating: 8.2, rtScore: 86, genres: ["Drama", "Mystery", "Thriller"] },
  { title: "Signs", year: 2002, imdbRating: 7.2, rtScore: 74, genres: ["Drama", "Mystery", "Sci-Fi"] },
  { title: "The Village", year: 2004, imdbRating: 6.5, rtScore: 43, genres: ["Drama", "Mystery", "Thriller"] },
  { title: "The Others", year: 2001, imdbRating: 7.6, rtScore: 83, genres: ["Drama", "Horror", "Mystery"] },
  { title: "28 Days Later", year: 2002, imdbRating: 7.6, rtScore: 87, genres: ["Drama", "Horror", "Sci-Fi"] },
  { title: "Dawn of the Dead", year: 2004, imdbRating: 7.3, rtScore: 75, genres: ["Action", "Horror"] },
  { title: "Shaun of the Dead", year: 2004, imdbRating: 7.9, rtScore: 92, genres: ["Comedy", "Horror"] },
  { title: "The Cabin in the Woods", year: 2011, imdbRating: 7.0, rtScore: 92, genres: ["Horror", "Mystery", "Thriller"] },
  { title: "Sinister", year: 2012, imdbRating: 6.8, rtScore: 63, genres: ["Horror", "Mystery", "Thriller"] },
  { title: "Insidious", year: 2010, imdbRating: 6.8, rtScore: 66, genres: ["Horror", "Mystery", "Thriller"] },
  { title: "Midsommar", year: 2019, imdbRating: 7.1, rtScore: 83, genres: ["Drama", "Horror", "Mystery"] },
  { title: "The Lighthouse", year: 2019, imdbRating: 7.5, rtScore: 90, genres: ["Drama", "Fantasy", "Horror"] },
  { title: "The Witch", year: 2015, imdbRating: 6.9, rtScore: 91, genres: ["Horror", "Mystery"] },
  { title: "Annihilation", year: 2018, imdbRating: 6.8, rtScore: 88, genres: ["Adventure", "Drama", "Horror"] },
  { title: "Mandy", year: 2018, imdbRating: 6.5, rtScore: 90, genres: ["Action", "Fantasy", "Horror"] },
  { title: "Suspiria", year: 2018, imdbRating: 6.8, rtScore: 84, genres: ["Drama", "Horror", "Mystery"] },
  { title: "Hereditary", year: 2018, imdbRating: 7.3, rtScore: 90, genres: ["Drama", "Horror", "Mystery"] },
  // Comedy
  { title: "The Grand Budapest Hotel", year: 2014, imdbRating: 8.1, rtScore: 91, genres: ["Adventure", "Comedy", "Crime"] },
  { title: "Moonrise Kingdom", year: 2012, imdbRating: 7.8, rtScore: 94, genres: ["Adventure", "Comedy", "Drama"] },
  { title: "The Royal Tenenbaums", year: 2001, imdbRating: 7.6, rtScore: 80, genres: ["Comedy", "Drama"] },
  { title: "Rushmore", year: 1998, imdbRating: 7.6, rtScore: 89, genres: ["Comedy", "Drama", "Romance"] },
  { title: "Bottle Rocket", year: 1996, imdbRating: 7.0, rtScore: 85, genres: ["Comedy", "Crime"] },
  { title: "Groundhog Day", year: 1993, imdbRating: 8.1, rtScore: 96, genres: ["Comedy", "Fantasy", "Romance"] },
  { title: "Home Alone", year: 1990, imdbRating: 7.7, rtScore: 66, genres: ["Comedy", "Family"] },
  { title: "Mrs. Doubtfire", year: 1993, imdbRating: 7.1, rtScore: 71, genres: ["Comedy", "Drama", "Family"] },
  { title: "Ace Ventura: Pet Detective", year: 1994, imdbRating: 6.9, rtScore: 45, genres: ["Comedy"] },
  { title: "The Mask", year: 1994, imdbRating: 6.9, rtScore: 79, genres: ["Action", "Comedy", "Crime"] },
  { title: "Dumb and Dumber", year: 1994, imdbRating: 7.3, rtScore: 64, genres: ["Comedy"] },
  { title: "Liar Liar", year: 1997, imdbRating: 6.9, rtScore: 82, genres: ["Comedy", "Fantasy"] },
  { title: "The Truman Show", year: 1998, imdbRating: 8.2, rtScore: 95, genres: ["Comedy", "Drama", "Sci-Fi"] },
  { title: "Bruce Almighty", year: 2003, imdbRating: 6.8, rtScore: 48, genres: ["Comedy", "Drama", "Fantasy"] },
  { title: "Eternal Sunshine of the Spotless Mind", year: 2004, imdbRating: 8.3, rtScore: 93, genres: ["Drama", "Romance", "Sci-Fi"] },
  { title: "Anchorman: The Legend of Ron Burgundy", year: 2004, imdbRating: 7.2, rtScore: 66, genres: ["Comedy"] },
  { title: "Step Brothers", year: 2008, imdbRating: 6.9, rtScore: 55, genres: ["Comedy"] },
  { title: "The Hangover", year: 2009, imdbRating: 7.7, rtScore: 79, genres: ["Comedy"] },
  { title: "Superbad", year: 2007, imdbRating: 7.6, rtScore: 88, genres: ["Comedy"] },
  { title: "Knocked Up", year: 2007, imdbRating: 7.1, rtScore: 90, genres: ["Comedy", "Drama", "Romance"] },
  { title: "Bridesmaids", year: 2011, imdbRating: 6.8, rtScore: 90, genres: ["Comedy", "Romance"] },
  { title: "The 40-Year-Old Virgin", year: 2005, imdbRating: 7.1, rtScore: 85, genres: ["Comedy", "Romance"] },
  { title: "Forgetting Sarah Marshall", year: 2008, imdbRating: 7.1, rtScore: 85, genres: ["Comedy", "Drama", "Romance"] },
  { title: "Tropic Thunder", year: 2008, imdbRating: 7.1, rtScore: 82, genres: ["Action", "Comedy"] },
  { title: "This Is the End", year: 2013, imdbRating: 6.6, rtScore: 83, genres: ["Comedy", "Fantasy"] },
  { title: "Game Night", year: 2018, imdbRating: 7.0, rtScore: 85, genres: ["Action", "Comedy", "Crime"] },
  { title: "Crazy Rich Asians", year: 2018, imdbRating: 6.9, rtScore: 91, genres: ["Comedy", "Drama", "Romance"] },
  { title: "Booksmart", year: 2019, imdbRating: 7.2, rtScore: 97, genres: ["Comedy"] },
  { title: "Palm Springs", year: 2020, imdbRating: 7.4, rtScore: 96, genres: ["Comedy", "Fantasy", "Mystery"] },
  { title: "Free Guy", year: 2021, imdbRating: 7.1, rtScore: 81, genres: ["Action", "Adventure", "Comedy"] },
  // Sci-Fi
  { title: "Interstellar", year: 2014, imdbRating: 8.7, rtScore: 72, genres: ["Adventure", "Drama", "Sci-Fi"] },
  { title: "Inception", year: 2010, imdbRating: 8.8, rtScore: 87, genres: ["Action", "Adventure", "Sci-Fi"] },
  { title: "Tenet", year: 2020, imdbRating: 7.4, rtScore: 70, genres: ["Action", "Sci-Fi", "Thriller"] },
  { title: "Dunkirk", year: 2017, imdbRating: 7.9, rtScore: 92, genres: ["Action", "Drama", "History"] },
  { title: "The Prestige", year: 2006, imdbRating: 8.5, rtScore: 76, genres: ["Drama", "Mystery", "Sci-Fi"] },
  { title: "Dune", year: 2021, imdbRating: 8.0, rtScore: 83, genres: ["Action", "Adventure", "Drama"] },
  { title: "Arrival", year: 2016, imdbRating: 7.9, rtScore: 94, genres: ["Drama", "Mystery", "Sci-Fi"] },
  { title: "Gravity", year: 2013, imdbRating: 7.7, rtScore: 96, genres: ["Drama", "Sci-Fi", "Thriller"] },
  { title: "The Martian", year: 2015, imdbRating: 8.0, rtScore: 91, genres: ["Adventure", "Drama", "Sci-Fi"] },
  { title: "Ex Machina", year: 2014, imdbRating: 7.7, rtScore: 92, genres: ["Drama", "Sci-Fi", "Thriller"] },
  { title: "Her", year: 2013, imdbRating: 8.0, rtScore: 94, genres: ["Drama", "Romance", "Sci-Fi"] },
  { title: "Moon", year: 2009, imdbRating: 7.9, rtScore: 89, genres: ["Drama", "Mystery", "Sci-Fi"] },
  { title: "Source Code", year: 2011, imdbRating: 7.5, rtScore: 91, genres: ["Action", "Mystery", "Sci-Fi"] },
  { title: "Looper", year: 2012, imdbRating: 7.4, rtScore: 93, genres: ["Action", "Drama", "Sci-Fi"] },
  { title: "Edge of Tomorrow", year: 2014, imdbRating: 7.9, rtScore: 91, genres: ["Action", "Adventure", "Sci-Fi"] },
  { title: "Oblivion", year: 2013, imdbRating: 7.0, rtScore: 54, genres: ["Action", "Adventure", "Mystery"] },
  { title: "Pacific Rim", year: 2013, imdbRating: 7.0, rtScore: 72, genres: ["Action", "Adventure", "Sci-Fi"] },
  { title: "Elysium", year: 2013, imdbRating: 6.6, rtScore: 68, genres: ["Action", "Drama", "Sci-Fi"] },
  { title: "Snowpiercer", year: 2013, imdbRating: 7.1, rtScore: 95, genres: ["Action", "Drama", "Sci-Fi"] },
  { title: "Coherence", year: 2013, imdbRating: 7.2, rtScore: 88, genres: ["Mystery", "Sci-Fi", "Thriller"] },
  { title: "Under the Skin", year: 2013, imdbRating: 6.3, rtScore: 86, genres: ["Drama", "Horror", "Sci-Fi"] },
  { title: "Predestination", year: 2014, imdbRating: 7.5, rtScore: 84, genres: ["Drama", "Mystery", "Sci-Fi"] },
  { title: "The Lobster", year: 2015, imdbRating: 7.1, rtScore: 88, genres: ["Comedy", "Drama", "Romance"] },
  { title: "Midnight Special", year: 2016, imdbRating: 6.7, rtScore: 81, genres: ["Adventure", "Drama", "Sci-Fi"] },
  { title: "Arrival", year: 2016, imdbRating: 7.9, rtScore: 94, genres: ["Drama", "Mystery", "Sci-Fi"] },
  { title: "Life", year: 2017, imdbRating: 6.6, rtScore: 67, genres: ["Horror", "Mystery", "Sci-Fi"] },
  { title: "Upgrade", year: 2018, imdbRating: 7.5, rtScore: 87, genres: ["Action", "Sci-Fi", "Thriller"] },
  { title: "Prospect", year: 2018, imdbRating: 6.7, rtScore: 88, genres: ["Adventure", "Drama", "Sci-Fi"] },
  { title: "Alita: Battle Angel", year: 2019, imdbRating: 7.3, rtScore: 61, genres: ["Action", "Adventure", "Sci-Fi"] },
  { title: "Ad Astra", year: 2019, imdbRating: 6.5, rtScore: 83, genres: ["Adventure", "Drama", "Mystery"] },
  { title: "High Life", year: 2018, imdbRating: 6.3, rtScore: 81, genres: ["Drama", "Sci-Fi", "Thriller"] },
  { title: "Possessor", year: 2020, imdbRating: 6.8, rtScore: 95, genres: ["Horror", "Sci-Fi", "Thriller"] },
  { title: "The Tomorrow War", year: 2021, imdbRating: 6.7, rtScore: 52, genres: ["Action", "Adventure", "Sci-Fi"] },
  { title: "Finch", year: 2021, imdbRating: 7.4, rtScore: 70, genres: ["Drama", "Sci-Fi"] },
  // Animation
  { title: "Toy Story 2", year: 1999, imdbRating: 7.9, rtScore: 100, genres: ["Animation", "Adventure", "Comedy"] },
  { title: "Toy Story 3", year: 2010, imdbRating: 8.3, rtScore: 98, genres: ["Animation", "Adventure", "Comedy"] },
  { title: "Toy Story 4", year: 2019, imdbRating: 7.7, rtScore: 97, genres: ["Animation", "Adventure", "Comedy"] },
  { title: "Finding Nemo", year: 2003, imdbRating: 8.2, rtScore: 99, genres: ["Animation", "Adventure", "Comedy"] },
  { title: "Finding Dory", year: 2016, imdbRating: 7.3, rtScore: 94, genres: ["Animation", "Adventure", "Comedy"] },
  { title: "The Incredibles", year: 2004, imdbRating: 8.0, rtScore: 97, genres: ["Animation", "Action", "Adventure"] },
  { title: "Incredibles 2", year: 2018, imdbRating: 7.6, rtScore: 93, genres: ["Animation", "Action", "Adventure"] },
  { title: "Monsters, Inc.", year: 2001, imdbRating: 8.1, rtScore: 96, genres: ["Animation", "Adventure", "Comedy"] },
  { title: "Monsters University", year: 2013, imdbRating: 7.3, rtScore: 80, genres: ["Animation", "Adventure", "Comedy"] },
  { title: "Ratatouille", year: 2007, imdbRating: 8.1, rtScore: 96, genres: ["Animation", "Comedy", "Family"] },
  { title: "Brave", year: 2012, imdbRating: 7.1, rtScore: 78, genres: ["Animation", "Adventure", "Comedy"] },
  { title: "Inside Out", year: 2015, imdbRating: 8.2, rtScore: 98, genres: ["Animation", "Adventure", "Comedy"] },
  { title: "Coco", year: 2017, imdbRating: 8.4, rtScore: 97, genres: ["Animation", "Adventure", "Comedy"] },
  { title: "Soul", year: 2020, imdbRating: 8.1, rtScore: 95, genres: ["Animation", "Adventure", "Comedy"] },
  { title: "Luca", year: 2021, imdbRating: 7.4, rtScore: 91, genres: ["Animation", "Adventure", "Comedy"] },
  { title: "Turning Red", year: 2022, imdbRating: 7.0, rtScore: 95, genres: ["Animation", "Adventure", "Comedy"] },
  { title: "Elemental", year: 2023, imdbRating: 6.9, rtScore: 73, genres: ["Animation", "Adventure", "Comedy"] },
  { title: "Shrek", year: 2001, imdbRating: 7.9, rtScore: 88, genres: ["Animation", "Adventure", "Comedy"] },
  { title: "Shrek 2", year: 2004, imdbRating: 7.3, rtScore: 89, genres: ["Animation", "Adventure", "Comedy"] },
  { title: "Kung Fu Panda", year: 2008, imdbRating: 7.6, rtScore: 87, genres: ["Animation", "Action", "Adventure"] },
  { title: "How to Train Your Dragon", year: 2010, imdbRating: 8.1, rtScore: 99, genres: ["Animation", "Action", "Adventure"] },
  { title: "The Secret Life of Pets", year: 2016, imdbRating: 6.5, rtScore: 74, genres: ["Animation", "Adventure", "Comedy"] },
  { title: "Zootopia", year: 2016, imdbRating: 8.0, rtScore: 98, genres: ["Animation", "Adventure", "Comedy"] },
  { title: "Moana", year: 2016, imdbRating: 7.6, rtScore: 95, genres: ["Animation", "Adventure", "Comedy"] },
  { title: "Frozen", year: 2013, imdbRating: 7.4, rtScore: 90, genres: ["Animation", "Adventure", "Comedy"] },
  { title: "Frozen II", year: 2019, imdbRating: 6.8, rtScore: 77, genres: ["Animation", "Adventure", "Comedy"] },
  { title: "Tangled", year: 2010, imdbRating: 7.7, rtScore: 89, genres: ["Animation", "Adventure", "Comedy"] },
  { title: "Encanto", year: 2021, imdbRating: 7.2, rtScore: 91, genres: ["Animation", "Comedy", "Family"] },
  { title: "Raya and the Last Dragon", year: 2021, imdbRating: 7.3, rtScore: 94, genres: ["Animation", "Action", "Adventure"] },
  { title: "The Nightmare Before Christmas", year: 1993, imdbRating: 8.0, rtScore: 95, genres: ["Animation", "Fantasy", "Musical"] },
  { title: "Coraline", year: 2009, imdbRating: 7.7, rtScore: 90, genres: ["Animation", "Drama", "Fantasy"] },
  { title: "Kubo and the Two Strings", year: 2016, imdbRating: 7.8, rtScore: 97, genres: ["Animation", "Action", "Adventure"] },
  { title: "Isle of Dogs", year: 2018, imdbRating: 7.9, rtScore: 90, genres: ["Animation", "Adventure", "Comedy"] },
  { title: "The Mitchells vs. the Machines", year: 2021, imdbRating: 7.7, rtScore: 97, genres: ["Animation", "Action", "Adventure"] },
  { title: "Wolfwalkers", year: 2020, imdbRating: 8.1, rtScore: 99, genres: ["Animation", "Adventure", "Fantasy"] },
  // Romance
  { title: "Notting Hill", year: 1999, imdbRating: 7.1, rtScore: 83, genres: ["Comedy", "Drama", "Romance"] },
  { title: "Love Actually", year: 2003, imdbRating: 7.6, rtScore: 63, genres: ["Comedy", "Drama", "Romance"] },
  { title: "About Time", year: 2013, imdbRating: 7.8, rtScore: 70, genres: ["Comedy", "Drama", "Fantasy"] },
  { title: "The Notebook", year: 2004, imdbRating: 7.8, rtScore: 53, genres: ["Drama", "Romance"] },
  { title: "Before Sunrise", year: 1995, imdbRating: 8.1, rtScore: 100, genres: ["Drama", "Romance"] },
  { title: "Before Sunset", year: 2004, imdbRating: 8.1, rtScore: 100, genres: ["Drama", "Romance"] },
  { title: "Before Midnight", year: 2013, imdbRating: 7.9, rtScore: 98, genres: ["Drama", "Romance"] },
  { title: "500 Days of Summer", year: 2009, imdbRating: 7.7, rtScore: 87, genres: ["Comedy", "Drama", "Romance"] },
  { title: "Silver Linings Playbook", year: 2012, imdbRating: 7.7, rtScore: 92, genres: ["Comedy", "Drama", "Romance"] },
  { title: "The Fault in Our Stars", year: 2014, imdbRating: 7.7, rtScore: 81, genres: ["Drama", "Romance"] },
  { title: "La La Land", year: 2016, imdbRating: 8.0, rtScore: 91, genres: ["Comedy", "Drama", "Musical"] },
  { title: "Crazy, Stupid, Love.", year: 2011, imdbRating: 7.4, rtScore: 78, genres: ["Comedy", "Drama", "Romance"] },
  { title: "The Proposal", year: 2009, imdbRating: 6.7, rtScore: 43, genres: ["Comedy", "Romance"] },
  { title: "Hitch", year: 2005, imdbRating: 6.6, rtScore: 69, genres: ["Comedy", "Romance"] },
  { title: "When Harry Met Sally...", year: 1989, imdbRating: 7.7, rtScore: 89, genres: ["Comedy", "Drama", "Romance"] },
  { title: "Pretty Woman", year: 1990, imdbRating: 7.0, rtScore: 63, genres: ["Comedy", "Romance"] },
  { title: "Sleepless in Seattle", year: 1993, imdbRating: 6.8, rtScore: 76, genres: ["Comedy", "Drama", "Romance"] },
  { title: "You've Got Mail", year: 1998, imdbRating: 6.7, rtScore: 69, genres: ["Comedy", "Drama", "Romance"] },
  { title: "Bridget Jones's Diary", year: 2001, imdbRating: 6.7, rtScore: 81, genres: ["Comedy", "Drama", "Romance"] },
  { title: "My Big Fat Greek Wedding", year: 2002, imdbRating: 6.6, rtScore: 76, genres: ["Comedy", "Romance"] },
  // Crime/Thriller
  { title: "Heat", year: 1995, imdbRating: 8.3, rtScore: 86, genres: ["Action", "Crime", "Drama"] },
  { title: "Collateral", year: 2004, imdbRating: 7.6, rtScore: 87, genres: ["Action", "Crime", "Drama"] },
  { title: "Miami Vice", year: 2006, imdbRating: 6.7, rtScore: 67, genres: ["Action", "Crime", "Drama"] },
  { title: "The Insider", year: 1999, imdbRating: 7.8, rtScore: 96, genres: ["Biography", "Crime", "Drama"] },
  { title: "Ali", year: 2001, imdbRating: 6.8, rtScore: 67, genres: ["Biography", "Drama", "Sport"] },
  { title: "Zodiac", year: 2007, imdbRating: 7.7, rtScore: 89, genres: ["Crime", "Drama", "Mystery"] },
  { title: "The Girl with the Dragon Tattoo", year: 2011, imdbRating: 7.8, rtScore: 88, genres: ["Crime", "Drama", "Mystery"] },
  { title: "Gone Girl", year: 2014, imdbRating: 8.1, rtScore: 87, genres: ["Drama", "Mystery", "Thriller"] },
  { title: "Se7en", year: 1995, imdbRating: 8.6, rtScore: 81, genres: ["Crime", "Drama", "Mystery"] },
  { title: "Prisoners", year: 2013, imdbRating: 8.1, rtScore: 81, genres: ["Crime", "Drama", "Mystery"] },
  { title: "Enemy", year: 2013, imdbRating: 7.0, rtScore: 90, genres: ["Drama", "Mystery", "Thriller"] },
  { title: "Sicario", year: 2015, imdbRating: 7.6, rtScore: 93, genres: ["Action", "Crime", "Drama"] },
  { title: "Sicario: Day of the Soldado", year: 2018, imdbRating: 7.1, rtScore: 63, genres: ["Action", "Crime", "Drama"] },
  { title: "Hell or High Water", year: 2016, imdbRating: 7.6, rtScore: 97, genres: ["Crime", "Drama", "Western"] },
  { title: "Wind River", year: 2017, imdbRating: 7.7, rtScore: 87, genres: ["Crime", "Drama", "Mystery"] },
  { title: "Widows", year: 2018, imdbRating: 7.0, rtScore: 91, genres: ["Crime", "Drama", "Thriller"] },
  { title: "The Town", year: 2010, imdbRating: 7.5, rtScore: 94, genres: ["Crime", "Drama", "Thriller"] },
  { title: "Heat", year: 1995, imdbRating: 8.3, rtScore: 86, genres: ["Action", "Crime", "Drama"] },
  { title: "Uncut Gems", year: 2019, imdbRating: 7.4, rtScore: 92, genres: ["Crime", "Drama", "Thriller"] },
  { title: "Good Time", year: 2017, imdbRating: 7.4, rtScore: 91, genres: ["Crime", "Drama", "Thriller"] },
  { title: "Nightcrawler", year: 2014, imdbRating: 7.9, rtScore: 95, genres: ["Crime", "Drama", "Thriller"] },
  { title: "Drive", year: 2011, imdbRating: 7.8, rtScore: 93, genres: ["Crime", "Drama"] },
  { title: "Only God Forgives", year: 2013, imdbRating: 5.7, rtScore: 40, genres: ["Crime", "Drama", "Thriller"] },
  { title: "The Neon Demon", year: 2016, imdbRating: 6.2, rtScore: 58, genres: ["Horror", "Mystery", "Thriller"] },
  { title: "Blade Runner 2049", year: 2017, imdbRating: 8.0, rtScore: 88, genres: ["Drama", "Mystery", "Sci-Fi"] },
  // International
  { title: "Amélie", year: 2001, imdbRating: 8.3, rtScore: 89, genres: ["Comedy", "Romance"] },
  { title: "The Intouchables", year: 2011, imdbRating: 8.5, rtScore: 75, genres: ["Biography", "Comedy", "Drama"] },
  { title: "Blue Is the Warmest Colour", year: 2013, imdbRating: 7.7, rtScore: 89, genres: ["Drama", "Romance"] },
  { title: "Portrait of a Lady on Fire", year: 2019, imdbRating: 8.1, rtScore: 98, genres: ["Drama", "History", "Romance"] },
  { title: "The Piano Teacher", year: 2001, imdbRating: 7.5, rtScore: 82, genres: ["Drama"] },
  { title: "Caché", year: 2005, imdbRating: 7.3, rtScore: 96, genres: ["Drama", "Mystery", "Thriller"] },
  { title: "The White Ribbon", year: 2009, imdbRating: 7.8, rtScore: 87, genres: ["Drama", "Mystery", "Thriller"] },
  { title: "Amour", year: 2012, imdbRating: 7.9, rtScore: 93, genres: ["Drama", "Romance"] },
  { title: "Funny Games", year: 1997, imdbRating: 7.6, rtScore: 76, genres: ["Crime", "Drama", "Thriller"] },
  { title: "The Lives of Others", year: 2006, imdbRating: 8.4, rtScore: 97, genres: ["Drama", "Thriller"] },
  { title: "Downfall", year: 2004, imdbRating: 8.2, rtScore: 91, genres: ["Biography", "Drama", "History"] },
  { title: "Run Lola Run", year: 1998, imdbRating: 7.7, rtScore: 94, genres: ["Action", "Crime", "Thriller"] },
  { title: "Das Boot", year: 1981, imdbRating: 8.4, rtScore: 99, genres: ["Action", "Drama", "War"] },
  { title: "Oldboy", year: 2003, imdbRating: 8.4, rtScore: 80, genres: ["Action", "Drama", "Mystery"] },
  { title: "The Handmaiden", year: 2016, imdbRating: 8.1, rtScore: 94, genres: ["Drama", "Mystery", "Romance"] },
  { title: "Burning", year: 2018, imdbRating: 7.5, rtScore: 99, genres: ["Drama", "Mystery", "Thriller"] },
  { title: "Train to Busan", year: 2016, imdbRating: 7.6, rtScore: 94, genres: ["Action", "Horror", "Thriller"] },
  { title: "A Separation", year: 2011, imdbRating: 8.3, rtScore: 99, genres: ["Drama"] },
  { title: "The Salesman", year: 2016, imdbRating: 7.8, rtScore: 97, genres: ["Crime", "Drama", "Thriller"] },
  { title: "Capernaum", year: 2018, imdbRating: 8.4, rtScore: 89, genres: ["Drama"] },
  { title: "Roma", year: 2018, imdbRating: 7.7, rtScore: 96, genres: ["Drama"] },
  { title: "Y Tu Mamá También", year: 2001, imdbRating: 7.7, rtScore: 91, genres: ["Drama", "Romance"] },
  { title: "Pan's Labyrinth", year: 2006, imdbRating: 8.2, rtScore: 95, genres: ["Drama", "Fantasy", "War"] },
  { title: "The Secret in Their Eyes", year: 2009, imdbRating: 8.2, rtScore: 91, genres: ["Crime", "Drama", "Mystery"] },
  { title: "Wild Tales", year: 2014, imdbRating: 8.1, rtScore: 93, genres: ["Comedy", "Drama", "Thriller"] },
  { title: "Shoplifters", year: 2018, imdbRating: 7.9, rtScore: 98, genres: ["Crime", "Drama"] },
  { title: "Drive My Car", year: 2021, imdbRating: 7.6, rtScore: 98, genres: ["Drama"] },
  { title: "Wheel of Fortune and Fantasy", year: 2021, imdbRating: 7.4, rtScore: 98, genres: ["Drama", "Romance"] },
  { title: "Decision to Leave", year: 2022, imdbRating: 7.4, rtScore: 97, genres: ["Crime", "Drama", "Mystery"] },
  { title: "Corsage", year: 2022, imdbRating: 7.0, rtScore: 91, genres: ["Biography", "Drama", "History"] },
  { title: "All Quiet on the Western Front", year: 2022, imdbRating: 7.8, rtScore: 91, genres: ["Drama", "War"] },
  { title: "Triangle of Sadness", year: 2022, imdbRating: 7.3, rtScore: 72, genres: ["Comedy", "Drama"] },
  { title: "The Zone of Interest", year: 2023, imdbRating: 7.4, rtScore: 93, genres: ["Drama", "History", "War"] },
  { title: "Anatomy of a Fall", year: 2023, imdbRating: 7.7, rtScore: 96, genres: ["Crime", "Drama", "Mystery"] },
  // Western
  { title: "Tombstone", year: 1993, imdbRating: 7.8, rtScore: 74, genres: ["Action", "Drama", "Western"] },
  { title: "Dances with Wolves", year: 1990, imdbRating: 8.0, rtScore: 81, genres: ["Adventure", "Drama", "Western"] },
  { title: "Lonesome Dove", year: 1989, imdbRating: 8.7, rtScore: 100, genres: ["Adventure", "Drama", "Western"] },
  { title: "True Grit", year: 2010, imdbRating: 7.6, rtScore: 96, genres: ["Adventure", "Drama", "Western"] },
  { title: "Django Unchained", year: 2012, imdbRating: 8.5, rtScore: 87, genres: ["Drama", "Western"] },
  { title: "The Hateful Eight", year: 2015, imdbRating: 7.8, rtScore: 74, genres: ["Crime", "Drama", "Mystery"] },
  { title: "Bone Tomahawk", year: 2015, imdbRating: 7.1, rtScore: 91, genres: ["Horror", "Western"] },
  { title: "Hostiles", year: 2017, imdbRating: 7.2, rtScore: 73, genres: ["Drama", "Western"] },
  { title: "The Assassination of Jesse James", year: 2007, imdbRating: 7.5, rtScore: 76, genres: ["Biography", "Crime", "Drama"] },
  { title: "Meek's Cutoff", year: 2010, imdbRating: 6.5, rtScore: 87, genres: ["Drama", "Western"] },
  // Music/Musical
  { title: "Whiplash", year: 2014, imdbRating: 8.5, rtScore: 94, genres: ["Drama", "Music"] },
  { title: "Straight Outta Compton", year: 2015, imdbRating: 7.9, rtScore: 88, genres: ["Biography", "Drama", "Music"] },
  { title: "Amy", year: 2015, imdbRating: 7.8, rtScore: 95, genres: ["Documentary", "Music"] },
  { title: "20 Feet from Stardom", year: 2013, imdbRating: 7.9, rtScore: 99, genres: ["Documentary", "Music"] },
  { title: "Searching for Sugar Man", year: 2012, imdbRating: 8.2, rtScore: 98, genres: ["Documentary", "Music"] },
  { title: "Anvil! The Story of Anvil", year: 2008, imdbRating: 7.8, rtScore: 97, genres: ["Documentary", "Music"] },
  { title: "The Last Waltz", year: 1978, imdbRating: 8.2, rtScore: 100, genres: ["Documentary", "Music"] },
  { title: "Stop Making Sense", year: 1984, imdbRating: 8.6, rtScore: 100, genres: ["Documentary", "Music"] },
  { title: "Woodstock", year: 1970, imdbRating: 8.0, rtScore: 100, genres: ["Documentary", "Music"] },
  { title: "Gimme Shelter", year: 1970, imdbRating: 8.1, rtScore: 100, genres: ["Documentary", "Music"] },
  // Documentary
  { title: "Bowling for Columbine", year: 2002, imdbRating: 8.0, rtScore: 96, genres: ["Documentary"] },
  { title: "Fahrenheit 9/11", year: 2004, imdbRating: 7.5, rtScore: 83, genres: ["Documentary"] },
  { title: "An Inconvenient Truth", year: 2006, imdbRating: 7.4, rtScore: 93, genres: ["Documentary"] },
  { title: "Man on Wire", year: 2008, imdbRating: 7.9, rtScore: 100, genres: ["Documentary"] },
  { title: "Exit Through the Gift Shop", year: 2010, imdbRating: 7.9, rtScore: 97, genres: ["Documentary"] },
  { title: "The Act of Killing", year: 2012, imdbRating: 8.2, rtScore: 97, genres: ["Documentary"] },
  { title: "Citizenfour", year: 2014, imdbRating: 8.0, rtScore: 97, genres: ["Documentary"] },
  { title: "I Am Not Your Negro", year: 2016, imdbRating: 7.9, rtScore: 99, genres: ["Documentary"] },
  { title: "Won't You Be My Neighbor?", year: 2018, imdbRating: 8.4, rtScore: 99, genres: ["Documentary"] },
  { title: "Free Solo", year: 2018, imdbRating: 8.2, rtScore: 100, genres: ["Documentary", "Sport"] },
  { title: "Apollo 11", year: 2019, imdbRating: 8.2, rtScore: 99, genres: ["Documentary", "History"] },
  { title: "The Rescue", year: 2021, imdbRating: 8.1, rtScore: 99, genres: ["Documentary"] },
  { title: "Summer of Soul", year: 2021, imdbRating: 8.1, rtScore: 99, genres: ["Documentary", "Music"] },
  { title: "All That Breathes", year: 2022, imdbRating: 7.8, rtScore: 99, genres: ["Documentary"] },
  { title: "All the Beauty and the Bloodshed", year: 2022, imdbRating: 7.9, rtScore: 99, genres: ["Documentary"] },
  { title: "Fire of Love", year: 2022, imdbRating: 7.9, rtScore: 99, genres: ["Documentary", "Romance"] },
  { title: "Navalny", year: 2022, imdbRating: 7.9, rtScore: 97, genres: ["Documentary"] },
  { title: "To Leslie", year: 2022, imdbRating: 7.2, rtScore: 89, genres: ["Drama"] },
  { title: "My Imaginary Country", year: 2022, imdbRating: 7.0, rtScore: 95, genres: ["Documentary"] },
  // Fantasy/Adventure
  { title: "The Lord of the Rings: The Fellowship of the Ring", year: 2001, imdbRating: 8.9, rtScore: 91, genres: ["Action", "Adventure", "Drama"] },
  { title: "The Lord of the Rings: The Two Towers", year: 2002, imdbRating: 8.8, rtScore: 95, genres: ["Action", "Adventure", "Drama"] },
  { title: "The Lord of the Rings: The Return of the King", year: 2003, imdbRating: 9.0, rtScore: 93, genres: ["Action", "Adventure", "Drama"] },
  { title: "The Hobbit: An Unexpected Journey", year: 2012, imdbRating: 7.8, rtScore: 64, genres: ["Adventure", "Fantasy"] },
  { title: "The Hobbit: The Desolation of Smaug", year: 2013, imdbRating: 7.9, rtScore: 74, genres: ["Adventure", "Fantasy"] },
  { title: "The Hobbit: The Battle of the Five Armies", year: 2014, imdbRating: 7.4, rtScore: 59, genres: ["Adventure", "Fantasy"] },
  { title: "Harry Potter and the Sorcerer's Stone", year: 2001, imdbRating: 7.6, rtScore: 81, genres: ["Adventure", "Family", "Fantasy"] },
  { title: "Harry Potter and the Chamber of Secrets", year: 2002, imdbRating: 7.4, rtScore: 82, genres: ["Adventure", "Family", "Fantasy"] },
  { title: "Harry Potter and the Prisoner of Azkaban", year: 2004, imdbRating: 7.9, rtScore: 90, genres: ["Adventure", "Family", "Fantasy"] },
  { title: "Harry Potter and the Goblet of Fire", year: 2005, imdbRating: 7.7, rtScore: 88, genres: ["Adventure", "Family", "Fantasy"] },
  { title: "Harry Potter and the Order of the Phoenix", year: 2007, imdbRating: 7.5, rtScore: 78, genres: ["Adventure", "Family", "Fantasy"] },
  { title: "Harry Potter and the Half-Blood Prince", year: 2009, imdbRating: 7.6, rtScore: 84, genres: ["Adventure", "Family", "Fantasy"] },
  { title: "Harry Potter and the Deathly Hallows – Part 1", year: 2010, imdbRating: 7.7, rtScore: 78, genres: ["Adventure", "Family", "Fantasy"] },
  { title: "Harry Potter and the Deathly Hallows – Part 2", year: 2011, imdbRating: 8.1, rtScore: 96, genres: ["Adventure", "Family", "Fantasy"] },
  { title: "The Chronicles of Narnia: The Lion, the Witch and the Wardrobe", year: 2005, imdbRating: 6.9, rtScore: 76, genres: ["Adventure", "Family", "Fantasy"] },
  { title: "Stardust", year: 2007, imdbRating: 7.6, rtScore: 77, genres: ["Adventure", "Family", "Fantasy"] },
  { title: "The Princess Bride", year: 1987, imdbRating: 8.1, rtScore: 97, genres: ["Adventure", "Family", "Fantasy"] },
  { title: "Labyrinth", year: 1986, imdbRating: 7.3, rtScore: 73, genres: ["Adventure", "Family", "Fantasy"] },
  { title: "The NeverEnding Story", year: 1984, imdbRating: 7.4, rtScore: 83, genres: ["Adventure", "Drama", "Family"] },
  { title: "Willow", year: 1988, imdbRating: 7.1, rtScore: 55, genres: ["Adventure", "Fantasy"] },
  // War
  { title: "Dunkirk", year: 2017, imdbRating: 7.9, rtScore: 92, genres: ["Action", "Drama", "History"] },
  { title: "Hacksaw Ridge", year: 2016, imdbRating: 8.1, rtScore: 84, genres: ["Biography", "Drama", "History"] },
  { title: "Fury", year: 2014, imdbRating: 7.6, rtScore: 79, genres: ["Action", "Drama", "War"] },
  { title: "Lone Survivor", year: 2013, imdbRating: 7.5, rtScore: 74, genres: ["Action", "Biography", "Drama"] },
  { title: "Zero Dark Thirty", year: 2012, imdbRating: 7.4, rtScore: 91, genres: ["Drama", "History", "Thriller"] },
  { title: "The Hurt Locker", year: 2008, imdbRating: 7.6, rtScore: 97, genres: ["Drama", "Thriller", "War"] },
  { title: "American Sniper", year: 2014, imdbRating: 7.3, rtScore: 72, genres: ["Action", "Biography", "Drama"] },
  { title: "Black Hawk Down", year: 2001, imdbRating: 7.7, rtScore: 76, genres: ["Action", "Drama", "History"] },
  { title: "We Were Soldiers", year: 2002, imdbRating: 7.2, rtScore: 64, genres: ["Action", "Drama", "History"] },
  { title: "Jarhead", year: 2005, imdbRating: 7.0, rtScore: 62, genres: ["Biography", "Drama", "War"] },
  { title: "The Thin Red Line", year: 1998, imdbRating: 7.6, rtScore: 78, genres: ["Drama", "War"] },
  { title: "Letters from Iwo Jima", year: 2006, imdbRating: 7.9, rtScore: 91, genres: ["Drama", "History", "War"] },
  { title: "Flags of Our Fathers", year: 2006, imdbRating: 7.1, rtScore: 73, genres: ["Drama", "History", "War"] },
  { title: "The Pianist", year: 2002, imdbRating: 8.5, rtScore: 95, genres: ["Biography", "Drama", "Music"] },
  { title: "Empire of the Sun", year: 1987, imdbRating: 7.8, rtScore: 79, genres: ["Drama", "History", "War"] },
  { title: "Come and See", year: 1985, imdbRating: 8.4, rtScore: 97, genres: ["Drama", "Thriller", "War"] },
  { title: "The Bridge on the Drina", year: 1974, imdbRating: 7.2, rtScore: 80, genres: ["Drama", "War"] },
  { title: "Paths of Glory", year: 1957, imdbRating: 8.4, rtScore: 95, genres: ["Drama", "War"] },
  { title: "The Bridge on the River Kwai", year: 1957, imdbRating: 8.2, rtScore: 95, genres: ["Adventure", "Drama", "War"] },
  { title: "Patton", year: 1970, imdbRating: 7.9, rtScore: 93, genres: ["Biography", "Drama", "History"] },
];

async function main() {
  console.log("🎬 CineVerse Extended Seed Starting...");
  const conn = await mysql.createConnection(DB_URL);

  // Get all genres
  const [genreRows] = await conn.execute("SELECT id, name FROM genres");
  const genreMap = {};
  for (const g of genreRows) genreMap[g.name] = g.id;

  let inserted = 0, skipped = 0;

  for (const movie of MOVIES) {
    try {
      const [existing] = await conn.execute(
        "SELECT id FROM movies WHERE title = ? AND year = ?",
        [movie.title, movie.year]
      );
      if (existing.length > 0) { skipped++; continue; }

      const slug = slugify(movie.title) + "-" + movie.year;
      const letter = movie.title.charAt(0).toUpperCase();
      const posterUrl = `https://placehold.co/300x450/1a1a1a/ff6b35?text=${encodeURIComponent(letter)}`;

      const [result] = await conn.execute(
        `INSERT INTO movies (title, slug, year, synopsis, imdbRating, rtScore, posterUrl, featured, trending)
         VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)`,
        [
          movie.title, slug, movie.year, null,
          movie.imdbRating || null, movie.rtScore || null, posterUrl,
          (movie.imdbRating || 0) >= 8.5 ? 1 : 0,
          (movie.year || 0) >= 2022 ? 1 : 0
        ]
      );

      const movieId = result.insertId;

      for (const genreName of movie.genres || []) {
        const genreId = genreMap[genreName];
        if (genreId) {
          await conn.execute(
            "INSERT IGNORE INTO movie_genres (movieId, genreId) VALUES (?, ?)",
            [movieId, genreId]
          );
        }
      }

      inserted++;
    } catch (err) {
      // Skip duplicates silently
    }
  }

  const [[{ total }]] = await conn.execute("SELECT COUNT(*) as total FROM movies");
  console.log(`✅ Inserted: ${inserted}, Skipped: ${skipped}`);
  console.log(`📊 Total movies in database: ${total}`);
  await conn.end();
}

main().catch(console.error);
